export const allCards = {
        "heros": 
            [
                {
                    id: 1,
                    name: "darthvader",
                    attack: 4000,
                    defence: 3500,
                    image: "https://i.imgur.com/zSeZ5EJ.png",
                    type : 'epic_card',
                    mana : 9,
                    side : 'dark',
                    isDef : false,
                    wasDef : false,
                    maulCurse : {active : false, round : -1},
                    locked : {active : false, round : -1},
                    timesAttacked : 0,
                    immune : false,
                    forceChoke : 0,
                    forcePull : false,
                    sithBetrayal: -1,
                    forcePush : -1,
                    forcePull : false,
                    kyberCrystal : -1,
                    seducedOrRedeemed : false,
                    description : "Bring the Dark Side's deadliest warrior to the battlefield, where he can wipe out all enemies with a single command. Requires a Dark card to be played."
                },
                {
                    id: 2,
                    name: "anakin",
                    attack: 3500,
                    defence: 3500,
                    image: "https://i.imgur.com/9CIQ1kW.png",
                    type : 'epic_card',
                    mana : 8,
                    side : 'light',
                    isDef : false,
                    wasDef : false,
                    maulCurse : {active : false, round : -1},
                    locked : {active : false, round : -1},
                    timesAttacked : 0,
                    immune : false,
                    forceChoke : 0,
                    forcePull : false,
                    sithBetrayal: -1,
                    forcePush : -1,
                    forcePull : false,
                    kyberCrystal : -1,
                    seducedOrRedeemed : false,
                    description : "Anakin is a powerful warrior with +100 attack after winning battles. He is a shining beacon of strength, ready to lead you to victory."
                },
                {
                    id: 3,
                    name: "darthsidious",
                    attack: 3600,
                    defence: 3200,
                    image: "https://i.imgur.com/hdQeIO7.png",
                    type : 'epic_card',
                    mana : 8,
                    side : 'dark',
                    isDef : false,
                    wasDef : false,
                    revived : 0,
                    maulCurse : {active : false, round : -1},
                    locked : {active : false, round : -1},
                    timesAttacked : 0,
                    immune : false,
                    forceChoke : 0,
                    forcePull : false,
                    sithBetrayal: -1,
                    forcePush : -1,
                    forcePull : false,
                    kyberCrystal : -1,
                    seducedOrRedeemed : false,
                    description : "Darth Sidious is a powerful card that returns to the field once after being defeated in battle. He is a formidable presence, ready to lead you to victory."
                },
                {
                    id: 4,
                    name: "yoda",
                    attack: 3800,
                    defence: 3000,
                    image: "https://i.imgur.com/0CakKMs.png",
                    type : 'epic_card',
                    mana : 8,
                    side : 'light',
                    isDef : false,
                    wasDef : false,
                    maulCurse : {active : false, round : -1},
                    locked : {active : false, round : -1},
                    timesAttacked : 0,
                    immune : false,
                    forceChoke : 0,
                    forcePull : false,
                    sithBetrayal: -1,
                    forcePush : -1,
                    forcePull : false,
                    kyberCrystal : -1,
                    seducedOrRedeemed : false,
                    description : "Yoda is a powerful card that cannot be killed or debuffed by special effects. He is a shining beacon of resilience, his indomitable spirit guiding you to victory."
                },
                {
                    id: 5,
                    name: "obiwan",
                    attack: 2500,
                    defence: 4000,
                    image: "https://i.imgur.com/5PrvfKs.png",
                    type : 'epic_card',
                    mana : 7,
                    side : 'light',
                    isDef : false,
                    wasDef : false,
                    maulCurse : {active : false, round : -1},
                    locked : {active : false, round : -1},
                    timesAttacked : 0,
                    immune : false,
                    forceChoke : 0,
                    forcePull : false,
                    sithBetrayal: -1,
                    forcePush : -1,
                    forcePull : false,
                    kyberCrystal : -1,
                    seducedOrRedeemed : false,
                    description : "Obi-Wan Kenobi is a powerful card with defense equal to the highest enemy attack. He is a versatile warrior, ready to adapt to any situation and emerge victorious."
                },
                {
                    id: 6,
                    name: "luke",
                    attack: 3500,
                    defence: 2800,
                    image: "https://i.imgur.com/33ebuKF.png",
                    type : 'epic_card',
                    mana : 7,
                    side : 'light',
                    isDef : false,
                    wasDef : false,
                    maulCurse : {active : false, round : -1},
                    locked : {active : false, round : -1},
                    timesAttacked : 0,
                    immune : false,
                    forceChoke : 0,
                    forcePull : false,
                    sithBetrayal: -1,
                    forcePush : -1,
                    forcePull : false,
                    kyberCrystal : -1,
                    seducedOrRedeemed : false,
                    description : "Luke Skywalker is a powerful card that gains +100 attack for each dark side card on the field. He becomes stronger as the battle progresses and is a valuable asset in any deck."
                },
                {
                    id: 7,
                    name: "windu",
                    attack: 3000,
                    defence: 3000,
                    image: "https://i.imgur.com/33ebuKF.png",
                    type : 'epic_card',
                    mana : 6,
                    side : 'no_side',
                    isDef : false,
                    wasDef : false,
                    maulCurse : {active : false, round : -1},
                    locked : {active : false, round : -1},
                    timesAttacked : 0,
                    immune : false,
                    forceChoke : 0,
                    forcePull : false,
                    sithBetrayal: -1,
                    forcePush : -1,
                    forcePull : false,
                    kyberCrystal : -1,
                    seducedOrRedeemed : false,
                    description : "Mace Windu is a powerful and adaptable card, his ability to utilize both light and dark spells giving him a wide range of options in battle. His versatility and strength make him a valuable asset to have in any deck."
                },
                {
                    id: 8,
                    name: "dooku",
                    attack: 3300,
                    defence: 2600,
                    image: "https://i.imgur.com/pwU3g3l.png",
                    type : 'epic_card',
                    mana : 6,
                    side : 'dark',
                    isDef : false,
                    wasDef : false,
                    maulCurse : {active : false, round : -1},
                    locked : {active : false, round : -1},
                    timesAttacked : 0,
                    immune : false,
                    forceChoke : 0,
                    forcePull : false,
                    sithBetrayal: -1,
                    forcePush : -1,
                    forcePull : false,
                    kyberCrystal : -1,
                    seducedOrRedeemed : false,
                    description : "Count Dooku is a powerful card that can attack twice per turn, but cannot attack directly to points. He is a formidable opponent, but his limitations can also be a hindrance."
                },
                {
                    id: 9,
                    name: "kyloren",
                    attack: 3000,
                    defence: 2800,
                    image: "https://i.imgur.com/CTjr8WC.png",
                    type : 'epic_card',
                    mana : 6,
                    side : 'dark',
                    isDef : false,
                    wasDef : false,
                    maulCurse : {active : false, round : -1},
                    locked : {active : false, round : -1},
                    timesAttacked : 0,
                    immune : false,
                    forceChoke : 0,
                    forcePull : false,
                    sithBetrayal: -1,
                    forcePush : -1,
                    forcePull : false,
                    kyberCrystal : -1,
                    seducedOrRedeemed : false,
                    description : "Kylo Ren is a powerful card that reveals enemy hand cards while in play. He is a valuable asset, providing valuable information about your opponent's strategies."
                },
                {
                    id: 10,
                    name: "ahsoka",
                    attack: 3000,
                    defence: 2500,
                    image: "https://i.imgur.com/xAmdUk9.png",
                    type : 'epic_card',
                    mana : 5,
                    side : 'no_side',
                    isDef : false,
                    wasDef : false,
                    maulCurse : {active : false, round : -1},
                    locked : {active : false, round : -1},
                    timesAttacked : 0,
                    immune : false,
                    forceChoke : 0,
                    forcePull : false,
                    sithBetrayal: -1,
                    forcePush : -1,
                    forcePull : false,
                    kyberCrystal : -1,
                    seducedOrRedeemed : false,
                    description : "Ahsoka Tano is a powerful card that gains +300 attack when battling Light cards and decreases enemy stats by -500 when battling Dark cards. She is a formidable opponent and a valuable asset in any game."
                },
                {
                    id: 11,
                    name: "rey",
                    attack: 3200,
                    defence: 2000,
                    image: "https://i.imgur.com/cqclRMW.png",
                    type : 'epic_card',
                    mana : 6,
                    side : 'light',
                    isDef : false,
                    wasDef : false,
                    maulCurse : {active : false, round : -1},
                    locked : {active : false, round : -1},
                    timesAttacked : 0,
                    immune : false,
                    forceChoke : 0,
                    forcePull : false,
                    sithBetrayal: -1,
                    forcePush : -1,
                    forcePull : false,
                    kyberCrystal : -1,
                    seducedOrRedeemed : false,
                    description : "Rey Skywalker is a powerful card that can attack directly to points and switches to defense after every attack. She is a strategic and versatile warrior, ready to lead you to victory."
                },
                {
                    id: 12,
                    name: "quigon",
                    attack: 2800,
                    defence: 2200,
                    image: "https://i.imgur.com/4sWrMXj.png",
                    type : 'epic_card',
                    mana : 5,
                    side : 'light',
                    isDef : false,
                    wasDef : false,
                    maulCurse : {active : false, round : -1},
                    locked : {active : false, round : -1},
                    timesAttacked : 0,
                    immune : false,
                    forceChoke : 0,
                    forcePull : false,
                    sithBetrayal: -1,
                    forcePush : -1,
                    forcePull : false,
                    kyberCrystal : -1,
                    seducedOrRedeemed : false,
                    description : "Qui Gon Jinn is a unique card that flips a coin before attacking, resulting in +700 or -700 stats based on the outcome. He is a unpredictable but potentially strong card."
                },
                {
                    id: 13,
                    name: "maul",
                    attack: 2800,
                    defence: 2000,
                    image: "https://i.imgur.com/Lr6v5Ph.png",
                    type : 'epic_card',
                    mana : 5,
                    side : 'dark',
                    isDef : false,
                    wasDef : false,
                    maulCurse : {active : false, round : -1},
                    locked : {active : false, round : -1},
                    timesAttacked : 0,
                    immune : false,
                    forceChoke : 0,
                    forcePull : false,
                    sithBetrayal: -1,
                    forcePush : -1,
                    forcePull : false,
                    kyberCrystal : -1,
                    seducedOrRedeemed : false,
                    description : "Dark Maul is a powerful card with a deadly ability. If he dies in battle, he can attach himself to the enemy and strike on the next turn, destroying the enemy card. His fearsome presence and strategic abilities make him a formidable opponent in any card game."
                },
                {
                    id: 14,
                    name: "grievous",
                    attack: 2500,
                    defence: 2200,
                    image: "https://i.imgur.com/wwV6GNb.png",
                    type : 'epic_card',
                    mana : 5,
                    side : 'dark',
                    isDef : false,
                    wasDef : false,
                    maulCurse : {active : false, round : -1},
                    locked : {active : false, round : -1},
                    timesAttacked : 0,
                    immune : false,
                    forceChoke : 0,
                    forcePull : false,
                    sithBetrayal: -1,
                    forcePush : -1,
                    forcePull : false,
                    kyberCrystal : -1,
                    seducedOrRedeemed : false,
                    description : "General Grievous is a powerful card that summons two droids to fight alongside him when he is played. He is a formidable force on the battlefield, with strong leadership skills and strategic abilities."
                },
                {
                    id: 15,
                    name: "din_djarin",
                    attack: 2000,
                    defence: 1500,
                    image: "https://i.imgur.com/UZdmg99.png",
                    type : 'basic_card',
                    mana : 4,
                    side : 'no_side',
                    isDef : false,
                    wasDef : false,
                    maulCurse : {active : false, round : -1},
                    locked : {active : false, round : -1},
                    timesAttacked : 0,
                    immune : false,
                    forceChoke : 0,
                    forcePull : false,
                    sithBetrayal: -1,
                    forcePush : -1,
                    forcePull : false,
                    kyberCrystal : -1,
                    seducedOrRedeemed : false,
                    description : "Din Djarin is a formidable fighter and a skilled warrior who is known for his loyalty and adherence to a strict code of honor."
                },
                {
                    id: 16,
                    name: "chewbacca",
                    attack: 1500,
                    defence: 2000,
                    image: "https://i.imgur.com/ppnUzyP.png",
                    type : 'basic_card',
                    mana : 4,
                    side : 'no_side',
                    isDef : false,
                    wasDef : false,
                    maulCurse : {active : false, round : -1},
                    locked : {active : false, round : -1},
                    timesAttacked : 0,
                    immune : false,
                    forceChoke : 0,
                    forcePull : false,
                    sithBetrayal: -1,
                    forcePush : -1,
                    forcePull : false,
                    kyberCrystal : -1,
                    seducedOrRedeemed : false,
                    description : "Chewbacca is a Wookiee, a species of tall, hairy humanoids known for their loyalty and fighting abilities."
                },
                {
                    id: 17,
                    name: "captain_rex",
                    attack: 1900,
                    defence: 1500,
                    image: "https://i.imgur.com/Q8BJN5s.png",
                    type : 'basic_card',
                    mana : 3,
                    side : 'no_side',
                    isDef : false,
                    wasDef : false,
                    maulCurse : {active : false, round : -1},
                    locked : {active : false, round : -1},
                    timesAttacked : 0,
                    immune : false,
                    forceChoke : 0,
                    forcePull : false,
                    sithBetrayal: -1,
                    forcePush : -1,
                    forcePull : false,
                    kyberCrystal : -1,
                    seducedOrRedeemed : false,
                    description : "Chewbacca is a Wookiee, a species of tall, hairy humanoids known for their loyalty and fighting abilities."
                },
                {
                    id: 18,
                    name: "boba_fett",
                    attack: 1900,
                    defence: 1500,
                    image: "https://i.imgur.com/MG8zJXq.png",
                    type : 'basic_card',
                    mana : 3,
                    side : 'no_side',
                    isDef : false,
                    wasDef : false,
                    maulCurse : {active : false, round : -1},
                    locked : {active : false, round : -1},
                    timesAttacked : 0,
                    immune : false,
                    forceChoke : 0,
                    forcePull : false,
                    sithBetrayal: -1,
                    forcePush : -1,
                    forcePull : false,
                    kyberCrystal : -1,
                    seducedOrRedeemed : false,
                    description : "Boba Fett is a notorious bounty hunter known for his ruthless efficiency in capturing his targets."
                },
                {
                    id: 19,
                    name: "leia_organa",
                    attack: 1800,
                    defence: 1500,
                    image: "https://i.imgur.com/5CVrput.png",
                    type : 'basic_card',
                    mana : 3,
                    side : 'no_side',
                    isDef : false,
                    wasDef : false,
                    maulCurse : {active : false, round : -1},
                    locked : {active : false, round : -1},
                    timesAttacked : 0,
                    immune : false,
                    forceChoke : 0,
                    forcePull : false,
                    sithBetrayal: -1,
                    forcePush : -1,
                    forcePull : false,
                    kyberCrystal : -1,
                    seducedOrRedeemed : false,
                    description : "Leia is a leader of the Rebel Alliance and the daughter of Anakin Skywalker, also known as Darth Vader."
                },
                {
                    id: 20,
                    name: "han_solo",
                    attack: 1700,
                    defence: 1400,
                    image: "https://i.imgur.com/NOFyDng.png",
                    type : 'basic_card',
                    mana : 2,
                    side : 'no_side',
                    isDef : false,
                    wasDef : false,
                    maulCurse : {active : false, round : -1},
                    locked : {active : false, round : -1},
                    timesAttacked : 0,
                    immune : false,
                    forceChoke : 0,
                    forcePull : false,
                    sithBetrayal: -1,
                    forcePush : -1,
                    forcePull : false,
                    kyberCrystal : -1,
                    seducedOrRedeemed : false,
                    description : "Han Solo is a smuggler and pilot who becomes a key member of the Rebel Alliance."
                },
                {
                    id: 21,
                    name: "padme",
                    attack: 1600,
                    defence: 1200,
                    image: "https://i.imgur.com/4qvNTrH.png",
                    type : 'basic_card',
                    mana : 2,
                    side : 'no_side',
                    isDef : false,
                    wasDef : false,
                    maulCurse : {active : false, round : -1},
                    locked : {active : false, round : -1},
                    timesAttacked : 0,
                    immune : false,
                    forceChoke : 0,
                    forcePull : false,
                    sithBetrayal: -1,
                    forcePush : -1,
                    forcePull : false,
                    kyberCrystal : -1,
                    seducedOrRedeemed : false,
                    description : "Padmé is a diplomat and politician from the planet Naboo known for her strong sense of justice and dedication to peace."
                },
                {
                    id: 22,
                    name: "grogu",
                    attack: 1500,
                    defence: 1200,
                    image: "https://i.imgur.com/nrHeR0W.png",
                    type : 'basic_card',
                    mana : 2,
                    side : 'no_side',
                    isDef : false,
                    wasDef : false,
                    maulCurse : {active : false, round : -1},
                    locked : {active : false, round : -1},
                    timesAttacked : 0,
                    immune : false,
                    forceChoke : 0,
                    forcePull : false,
                    sithBetrayal: -1,
                    forcePush : -1,
                    forcePull : false,
                    kyberCrystal : -1,
                    seducedOrRedeemed : false,
                    description : "Despite his small size, Grogu is a formidable force in the Star Wars universe, inspiring loyalty and love in all who encounter him."
                },
                {
                    id: 23,
                    name: "r2d2",
                    attack: 1200,
                    defence: 1200,
                    image: "https://i.imgur.com/Wv39w8V.png",
                    type : 'basic_card',
                    mana : 1,
                    side : 'no_side',
                    isDef : false,
                    wasDef : false,
                    maulCurse : {active : false, round : -1},
                    locked : {active : false, round : -1},
                    timesAttacked : 0,
                    immune : false,
                    forceChoke : 0,
                    forcePull : false,
                    sithBetrayal: -1,
                    forcePush : -1,
                    forcePull : false,
                    kyberCrystal : -1,
                    seducedOrRedeemed : false,
                    description : "R2-D2 is a small, intelligent robot. It communicates through beeps and whistles and is known for its resourcefulness and bravery."
                },
                {
                    id: 24,
                    name: "bb8",
                    attack: 1100,
                    defence: 1100,
                    image: "https://i.imgur.com/wWBewqN.png",
                    type : 'basic_card',
                    mana : 1,
                    side : 'no_side',
                    isDef : false,
                    wasDef : false,
                    maulCurse : {active : false, round : -1},
                    locked : {active : false, round : -1},
                    timesAttacked : 0,
                    immune : false,
                    forceChoke : 0,
                    forcePull : false,
                    sithBetrayal: -1,
                    forcePush : -1,
                    forcePull : false,
                    kyberCrystal : -1,
                    seducedOrRedeemed : false,
                    description : "BB-8 is a spherical droid with a domed head that can move independently of its body."
                },
                {
                    id: 25,
                    name: "c3po",
                    attack: 1100,
                    defence: 1000,
                    image: "https://i.imgur.com/0lvAC6X.png",
                    type : 'basic_card',
                    mana : 1,
                    side : 'no_side',
                    isDef : false,
                    wasDef : false,
                    maulCurse : {active : false, round : -1},
                    locked : {active : false, round : -1},
                    timesAttacked : 0,
                    immune : false,
                    forceChoke : 0,
                    forcePull : false,
                    sithBetrayal: -1,
                    forcePush : -1,
                    forcePull : false,
                    kyberCrystal : -1,
                    seducedOrRedeemed : false,
                    description : "C-3PO is a protocol droid designed to assist with etiquette, customs, and translation, and is fluent in over six million forms of communication."
                },
                {
                    "id": 26,
                    "name": "special_deathstar",
                    "image": "https://i.imgur.com/CbqpPUz.png",
                    'type' : 'special',
                    'mana' : 8,
                    description : "Death Star: This powerful force card unleashes the devastating might of the Galactic Empire's most feared weapon. With a single blast from its planet-destroying superlaser, the Death Star can destroy any card in play, regardless of its strength or abilities. Whether you're facing down a formidable opponent or simply want to clear the field, the Death Star is a formidable tool in the hands of a skilled player. Use it wisely, and may the force be with you."
                },
                {
                    "id": 27,
                    "name": "special_forceghost",
                    "image": "https://i.imgur.com/Jwv5JuV.png",
                    'type' : 'special',
                    'mana' : 7,
                    description : "Force Ghost: This ethereal force card allows you to call upon the spirits of the Jedi to resurrect a fallen ally. By tapping into the power of the force, you can bring a light card back from the dead and return it to play, ready to fight for your cause once again. However, this powerful ability can only be used if you have at least one light card on the field, so plan your strategy carefully and choose your targets wisely. May the force be with you."
                },
                {
                    "id": 28,
                    "name": "special_order66",
                    "image": "https://i.imgur.com/wUuIk00.png",
                    'type' : 'special',
                    'mana' : 7,
                    description : "Order 66: This devastating force card allows you to call upon the dark side of the force to wipe out all light cards on the field. Named after the infamous command issued by Emperor Palpatine to exterminate the Jedi Order, Order 66 is a powerful tool for those who follow the dark side of the force. Whether you're facing down a powerful enemy or simply looking to clear the field, Order 66 is a formidable weapon in the hands of a skilled player.It can only be used if you have at least one dark card on the field so use it wisely, and may the force be with you."
                },
                {
                    "id": 29,
                    "name": "special_galacticrepublic",
                    "image": "https://i.imgur.com/rlAJKZp.png",
                    'type' : 'special',
                    'mana' : 6,
                    description : "Galactic Republic: This powerful force card allows you to call upon the strength and unity of the Galactic Republic to increase the stats of all light cards in play by +200. Whether you're facing down a formidable enemy or simply looking to give your light side forces a boost, the Galactic Republic is a valuable ally in any battle. However, it can only be used if you have at least one light card on the field, so plan your strategy carefully and choose your targets wisely. May the force be with you."
                },
                {
                    "id": 30,
                    "name": "special_galacticempire",
                    "image": "https://i.imgur.com/GzQphmd.png",
                    'type' : 'special',
                    'mana' : 6,
                    description : "Galactic Empire: This powerful force card allows you to call upon the strength and unity of the Galactic Empire to increase the stats of all dark cards in play by +200. Whether you're facing down a formidable enemy or simply looking to give your dark side forces a boost, the Galactic Empire is a valuable ally in any battle. However, it can only be used if you have at least one dark card on the field, so plan your strategy carefully and choose your targets wisely. May the force be with you."
                },
                {
                    "id": 31,
                    "name": "special_sithbetrayal",
                    "image": "https://i.imgur.com/0uew3aZ.png",
                    'type' : 'special',
                    'mana' : 5,
                    description : "Sith Betrayal: This treacherous force card allows you to sacrifice one of your own dark side cards to boost another card's stats by +500. Inspired by the infighting and backstabbing that has plagued the Sith Order for centuries, Sith Betrayal is a powerful tool for those who follow the dark side of the force. However, it can only be used if you have at least one dark card on the field, so choose your targets wisely and be prepared to pay the price for your ambition. May the force be with you."
                },
                {
                    "id": 32,
                    "name": "special_seduce",
                    "image": "https://i.imgur.com/gCdITRG.png",
                    'type' : 'special',
                    'mana' : 5,
                    description : "Seduce: This cunning force card allows you to use the dark side of the force to turn one of your enemy's cards to the dark side for a single turn. Whether you're facing down a powerful enemy or simply looking to gain an advantage, Seduce is a valuable tool for any Sith Lord or dark side adept. However, it can only be used if you have at least one dark card on the field, so plan your strategy carefully and choose your targets wisely. May the force be with you."
                },
                {
                    "id": 33,
                    "name": "special_jedimindtrick",
                    "image": "https://i.imgur.com/etZZTcA.png",
                    'type' : 'special',
                    'mana' : 5,
                    description : "Jedi Mind Trick: This cunning force card allows you to use the power of the force to bend the will of your enemies and turn them against their own side. By manipulating their thoughts and perceptions, you can choose one dark card to attack its own team for a single turn. Whether you're facing down a formidable enemy or simply looking to gain an advantage, the Jedi Mind Trick is a valuable tool for any Jedi Knight or light side adept. However, it can only be used if you have at least one light card on the field, so plan your strategy carefully and choose your targets wisely. May the force be with you."
                },
                {
                    "id": 34,
                    "name": "special_redeem",
                    "image": "https://i.imgur.com/dRagu4N.png",
                    'type' : 'special',
                    'mana' : 5,
                    description : "Redeem: This powerful force card allows you to use the light side of the force to turn one of your enemy's cards to the light side for a single turn. Whether you're facing down a formidable enemy or simply looking to gain an advantage, Redeem is a valuable tool for any Jedi Knight or light side adept. However, it can only be used if you have at least one light card on the field, so plan your strategy carefully and choose your targets wisely. May the force be with you."
                },
                {
                    "id": 35,
                    "name": "special_forcechoke",
                    "image": "https://i.imgur.com/ZGddAOL.png",
                    'type' : 'special',
                    'mana' : 4,
                    description : "Force Choke: This powerful force card allows you to use the dark side of the force to squeeze the life out of your enemies. By using the force to constrict their throats and cut off their air supply, you can make a light card bleed -200 for 3 turns. Whether you're facing down a formidable enemy or simply looking to gain an advantage, Force Choke is a valuable tool for any Sith Lord or dark side adept. However, it can only be used if you have at least one dark card on the field, so plan your strategy carefully and choose your targets wisely. May the force be with you."
                },
                {
                    "id": 36,
                    "name": "special_forcedrain",
                    "image": "https://i.imgur.com/Eboimo7.png",
                    'type' : 'special',
                    'mana' : 4,
                    description : "Force Drain: This powerful force card allows you to use the dark side of the force to drain the life force of your enemies. By tapping into their energy and stealing their strength, you can boost your own stats by +300. Whether you're facing down a formidable enemy or simply looking to gain an advantage, Force Drain is a valuable tool for any Sith Lord or dark side adept. However, it can only be used if you have at least one dark card on the field, so plan your strategy carefully and choose your targets wisely. May the force be with you."
                },
                {
                    "id": 37,
                    "name": "special_fulcrum",
                    "image": "https://i.imgur.com/64W2ITy.png",
                    'type' : 'special',
                    'mana' : 0,
                    description : "Fulcrum: This powerful force card allows you to call upon the wisdom and strength of Ahsoka Tano, the former Jedi Padawan turned rebel leader. By drawing upon her knowledge and experience, you can add an Ahsoka card to your hand, giving you access to her powerful abilities and tactics. Whether you're facing down a formidable enemy or simply looking to gain an advantage, Fulcrum is a valuable tool for any player seeking to harness the power of the force. May the force be with you."
                },
                {
                    "id": 38,
                    "name": "special_forceshield",
                    "image": "https://i.imgur.com/uOlaftZ.png",
                    'type' : 'special',
                    'mana' : 4,
                    description : "Force Shield: This powerful force card allows you to use the light side of the force to protect one of your light cards from harm. By creating a shield of energy around your chosen target, you can make it immune to damage for a single turn. Whether you're facing down a formidable enemy or simply looking to strengthen your defenses, Force Shield is a valuable tool for any Jedi Knight or light side adept. However, it can only be used if you have at least one light card on the field, so plan your strategy carefully and choose your targets wisely. May the force be with you."
                },
                {
                    "id": 39,
                    "name": "special_walloflight",
                    "image": "https://i.imgur.com/vsDKKce.png",
                    'type' : 'special',
                    'mana' : 4,
                    description : "Wall of Light: This powerful force card allows you to use the light side of the force to create a barrier of energy that blocks your enemies from attacking. By erecting a wall of light around one of your light cards, you can prevent a dark card from attacking for 2 turns. Whether you're facing down a formidable enemy or simply looking to strengthen your defenses, Wall of Light is a valuable tool for any Jedi Knight or light side adept. However, it can only be used if you have at least one light card on the field, so plan your strategy carefully and choose your targets wisely. May the force be with you."
                },
                {
                    "id": 40,
                    "name": "special_traiders",
                    "image": "https://i.imgur.com/5yo7k9E.png",
                    'type' : 'special',
                    'mana' : 3,
                    description : "Tusken Raiders: This cunning force card allows you to call upon the ferocity and cunning of the Tusken Raiders, the nomadic desert dwellers of Tatooine. By unleashing their brutal attacks and ambushes, you can prevent your enemy from using any force cards for a single turn. Whether you're facing down a formidable enemy or simply looking to gain an advantage, Tusken Raiders are a valuable ally in any battle. May the force be with you."
                },
                {
                    "id": 41,
                    "name": "special_forcepull",
                    "image": "https://i.imgur.com/K1Rzlkw.png",
                    'type' : 'special',
                    'mana' : 3,
                    description : "Force Pull: This powerful force card allows you to use the force to draw one of your cards closer to you, boosting its stats by +400. However, the force can be a fickle and unstable power, and using Force Pull comes with a price. Each round, the card's stats will decrease by -100, making it less powerful over time. Whether you're facing down a formidable enemy or simply looking to gain an advantage, Force Pull is a valuable tool for any master of the force. Use it wisely, and may the force be with you."
                },
                {
                    "id": 42,
                    "name": "special_forcelightning",
                    "image": "https://i.imgur.com/xZJrfu1.png",
                    'type' : 'special',
                    'mana' : 3,
                    description : "Force Lightning: This is a powerful and deadly ability wielded by skilled Force users, particularly those who embrace the dark side. This card allows you to unleash a devastating burst of electricity, dealing 1000 points of damage to your enemy. Be careful, however, as this dark power can have unintended consequences and may ultimately consume you."
                },
                {
                    "id": 43,
                    "name": "special_saberthrow",
                    "image": "https://i.imgur.com/eECGyTh.png",
                    'type' : 'special',
                    'mana' : 3,
                    description : "Saber Throw: This is a powerful and deadly technique used by skilled lightsaber wielders. This card allows you to hurl your lightsaber at your enemy, dealing 500 points of damage and preventing them from summoning any cards on their next turn. Be careful, however, as this technique requires precise aim and can leave you vulnerable if you miss."
                },
                {
                    "id": 44,
                    "name": "special_forcehealing",
                    "image": "https://i.imgur.com/ll131BJ.png",
                    'type' : 'special',
                    'mana' : 3,
                    description : "Force Healing: This technique is a powerful ability wielded by skilled Force users who embrace the light side of the Force. This card allows you to tap into the restorative power of the Force to heal yourself, restoring 1000 points of health. Use this card wisely, as it can be a valuable tool in the heat of battle."
                },
                {
                    "id": 45,
                    "name": "special_forcepush",
                    "image": "https://i.imgur.com/F0CZssw.png",
                    'type' : 'special',
                    'mana' : 3,
                    description : "Force Push: This is a powerful technique used by skilled Force users. This card allows you to use the Force to enhance any card for one round, increasing its stats by 300 points. Be strategic with this ability and use it to give yourself an advantage in battle, but be aware that the Force can be unpredictable and may not always work to your advantage."
                },
                {
                    "id": 46,
                    "name": "special_forcefreeze",
                    "image": "https://i.imgur.com/BQRFGdE.png",
                    'type' : 'special',
                    'mana' : 2,
                    description : "Force Freeze: This is a powerful technique used by skilled Force users. This card allows you to use the Force to temporarily freeze your enemy's card in place, changing its position for two turns. This can give you an advantage in battle by disrupting your enemy's strategy and allowing you to reposition your own cards for a better advantage. Be careful, however, as the Force can be unpredictable and may not always work in your favor."
                },
                {
                    "id": 47,
                    "name": "special_kybercrystal",
                    "image": "https://i.imgur.com/eX5XBjw.png",
                    'type' : 'special',
                    'mana' : 2,
                    description : "Kyber Crystals are rare and powerful crystals that are used to power lightsabers. This card allows you to tap into the energy of a Kyber Crystal to boost the attack of any card in your hand by 200 points. Use this card wisely to give yourself an advantage in battle, but be careful not to overuse it, as the power of the Kyber Crystal can be unpredictable and may not always work in your favor."
                },
                {
                    "id": 48,
                    "name": "special_binarysunset",
                    "image": "https://i.imgur.com/hXFjYYz.png",
                    'type' : 'special',
                    'mana' : 1,
                    description : "Binary Sunset : This card allows you to draw upon the energy of the Binary Sunset to draw two additional cards into your hand. Use this card wisely to increase your options and give yourself an advantage in battle, but be careful not to overuse it, as the power of the Binary Sunset can be unpredictable and may not always work in your favor."
                },
                {
                    "id": 49,
                    "name": "special_bactatank",
                    "image": "https://i.imgur.com/xNc0FnM.png",
                    'type' : 'special',
                    'mana' : 1,
                    description : "Bacta Tank: This special card allows you to refill your entire mana pool. Use it to gain an advantage in the game and keep your options open for future turns."
                },
                {
                    "id": 50,
                    "name": "special_meditation",
                    "image": "https://i.imgur.com/Xazuczw.png",
                    'type' : 'special',
                    'mana' : 0,
                    description : "Meditation: This force card allows you to tap into the calming power of the force, replenishing your mana reserves. By taking a moment to clear your mind and focus your energy, you can gain 1 mana point, which you can use to unleash powerful force abilities or strengthen your defenses. Whether you're facing down a fierce enemy or simply need to rest and regroup, Meditation is a valuable tool for any Jedi or Sith seeking to master the force."
                },
            ]
}

