export const forceCards = {
    heros: [
      {
        id: 1,
        name: "darthvader",
        attack: 4000,
        defence: 3500,
        image: "https://i.imgur.com/zSeZ5EJ.png",
        type: "epic_card",
        mana: 9,
        side: "dark",
        isDef: false,
        wasDef: false,
        maulCurse: { active: false, round: -1 },
        locked: { active: false, round: -1 },
        timesAttacked: 0,
        immune: false,
        forceChoke: 0,
        forcePull: false,
        sithBetrayal: -1,
        forcePush: -1,
        forcePull: false,
        kyberCrystal: -1,
        seducedOrRedeemed: false,
        description:
          "Bring the Dark Side's deadliest warrior to the battlefield, where he can wipe out all enemies with a single command. Requires a Dark card to be played.",
      },
      {
        id: 2,
        name: "anakin",
        attack: 3500,
        defence: 3500,
        image: "https://i.imgur.com/9CIQ1kW.png",
        type: "epic_card",
        mana: 8,
        side: "light",
        isDef: false,
        wasDef: false,
        maulCurse: { active: false, round: -1 },
        locked: { active: false, round: -1 },
        timesAttacked: 0,
        immune: false,
        forceChoke: 0,
        forcePull: false,
        sithBetrayal: -1,
        forcePush: -1,
        forcePull: false,
        kyberCrystal: -1,
        seducedOrRedeemed: false,
        description:
          "Anakin is a powerful warrior with +100 attack after winning battles. He is a shining beacon of strength, ready to lead you to victory.",
      },
      {
        id: 3,
        name: "darthsidious",
        attack: 3600,
        defence: 3200,
        image: "https://i.imgur.com/hdQeIO7.png",
        type: "epic_card",
        mana: 8,
        side: "dark",
        isDef: false,
        wasDef: false,
        revived: 0,
        maulCurse: { active: false, round: -1 },
        locked: { active: false, round: -1 },
        timesAttacked: 0,
        immune: false,
        forceChoke: 0,
        forcePull: false,
        sithBetrayal: -1,
        forcePush: -1,
        forcePull: false,
        kyberCrystal: -1,
        seducedOrRedeemed: false,
        description:
          "Darth Sidious is a powerful card that returns to the field once after being defeated in battle. He is a formidable presence, ready to lead you to victory.",
      },
      {
        id: 4,
        name: "yoda",
        attack: 3800,
        defence: 3000,
        image: "https://i.imgur.com/0CakKMs.png",
        type: "epic_card",
        mana: 8,
        side: "light",
        isDef: false,
        wasDef: false,
        maulCurse: { active: false, round: -1 },
        locked: { active: false, round: -1 },
        timesAttacked: 0,
        immune: false,
        forceChoke: 0,
        forcePull: false,
        sithBetrayal: -1,
        forcePush: -1,
        forcePull: false,
        kyberCrystal: -1,
        seducedOrRedeemed: false,
        description:
          "Yoda is a powerful card that cannot be killed or debuffed by special effects. He is a shining beacon of resilience, his indomitable spirit guiding you to victory.",
      },
      {
        id: 5,
        name: "obiwan",
        attack: 2500,
        defence: 4000,
        image: "https://i.imgur.com/5PrvfKs.png",
        type: "epic_card",
        mana: 7,
        side: "light",
        isDef: false,
        wasDef: false,
        maulCurse: { active: false, round: -1 },
        locked: { active: false, round: -1 },
        timesAttacked: 0,
        immune: false,
        forceChoke: 0,
        forcePull: false,
        sithBetrayal: -1,
        forcePush: -1,
        forcePull: false,
        kyberCrystal: -1,
        seducedOrRedeemed: false,
        description:
          "Obi-Wan Kenobi is a powerful card with defense equal to the highest enemy attack. He is a versatile warrior, ready to adapt to any situation and emerge victorious.",
      },
      {
        id: 6,
        name: "luke",
        attack: 3500,
        defence: 2800,
        image: "https://i.imgur.com/33ebuKF.png",
        type: "epic_card",
        mana: 7,
        side: "light",
        isDef: false,
        wasDef: false,
        maulCurse: { active: false, round: -1 },
        locked: { active: false, round: -1 },
        timesAttacked: 0,
        immune: false,
        forceChoke: 0,
        forcePull: false,
        sithBetrayal: -1,
        forcePush: -1,
        forcePull: false,
        kyberCrystal: -1,
        seducedOrRedeemed: false,
        description:
          "Luke Skywalker is a powerful card that gains +100 attack for each dark side card on the field. He becomes stronger as the battle progresses and is a valuable asset in any deck.",
      },
      {
        id: 7,
        name: "windu",
        attack: 3000,
        defence: 3000,
        image: "https://i.imgur.com/ofAvDHC.png",
        type: "epic_card",
        mana: 6,
        side: "no_side",
        isDef: false,
        wasDef: false,
        maulCurse: { active: false, round: -1 },
        locked: { active: false, round: -1 },
        timesAttacked: 0,
        immune: false,
        forceChoke: 0,
        forcePull: false,
        sithBetrayal: -1,
        forcePush: -1,
        forcePull: false,
        kyberCrystal: -1,
        seducedOrRedeemed: false,
        description:
          "Mace Windu is a powerful and adaptable card, his ability to utilize both light and dark spells giving him a wide range of options in battle. His versatility and strength make him a valuable asset to have in any deck.",
      },
      {
        id: 8,
        name: "dooku",
        attack: 3300,
        defence: 2600,
        image: "https://i.imgur.com/pwU3g3l.png",
        type: "epic_card",
        mana: 6,
        side: "dark",
        isDef: false,
        wasDef: false,
        maulCurse: { active: false, round: -1 },
        locked: { active: false, round: -1 },
        timesAttacked: 0,
        immune: false,
        forceChoke: 0,
        forcePull: false,
        sithBetrayal: -1,
        forcePush: -1,
        forcePull: false,
        kyberCrystal: -1,
        seducedOrRedeemed: false,
        description:
          "Count Dooku is a powerful card that can attack twice per turn, but cannot attack directly to points. He is a formidable opponent, but his limitations can also be a hindrance.",
      },
      {
        id: 9,
        name: "kyloren",
        attack: 3000,
        defence: 2800,
        image: "https://i.imgur.com/CTjr8WC.png",
        type: "epic_card",
        mana: 6,
        side: "dark",
        isDef: false,
        wasDef: false,
        maulCurse: { active: false, round: -1 },
        locked: { active: false, round: -1 },
        timesAttacked: 0,
        immune: false,
        forceChoke: 0,
        forcePull: false,
        sithBetrayal: -1,
        forcePush: -1,
        forcePull: false,
        kyberCrystal: -1,
        seducedOrRedeemed: false,
        description:
          "Kylo Ren is a powerful card that reveals enemy hand cards while in play. He is a valuable asset, providing valuable information about your opponent's strategies.",
      },
      {
        id: 10,
        name: "ahsoka",
        attack: 3000,
        defence: 2500,
        image: "https://i.imgur.com/xAmdUk9.png",
        type: "epic_card",
        mana: 5,
        side: "no_side",
        isDef: false,
        wasDef: false,
        maulCurse: { active: false, round: -1 },
        locked: { active: false, round: -1 },
        timesAttacked: 0,
        immune: false,
        forceChoke: 0,
        forcePull: false,
        sithBetrayal: -1,
        forcePush: -1,
        forcePull: false,
        kyberCrystal: -1,
        seducedOrRedeemed: false,
        description:
          "Ahsoka Tano is a powerful card that gains +300 attack when battling Light cards and decreases enemy stats by -500 when battling Dark cards. She is a formidable opponent and a valuable asset in any game.",
      },
      {
        id: 11,
        name: "rey",
        attack: 3200,
        defence: 2000,
        image: "https://i.imgur.com/cqclRMW.png",
        type: "epic_card",
        mana: 6,
        side: "light",
        isDef: false,
        wasDef: false,
        maulCurse: { active: false, round: -1 },
        locked: { active: false, round: -1 },
        timesAttacked: 0,
        immune: false,
        forceChoke: 0,
        forcePull: false,
        sithBetrayal: -1,
        forcePush: -1,
        forcePull: false,
        kyberCrystal: -1,
        seducedOrRedeemed: false,
        description:
          "Rey Skywalker is a powerful card that can attack directly to points and switches to defense after every attack. She is a strategic and versatile warrior, ready to lead you to victory.",
      },
      {
        id: 12,
        name: "quigon",
        attack: 2800,
        defence: 2200,
        image: "https://i.imgur.com/4sWrMXj.png",
        type: "epic_card",
        mana: 5,
        side: "light",
        isDef: false,
        wasDef: false,
        maulCurse: { active: false, round: -1 },
        locked: { active: false, round: -1 },
        timesAttacked: 0,
        immune: false,
        forceChoke: 0,
        forcePull: false,
        sithBetrayal: -1,
        forcePush: -1,
        forcePull: false,
        kyberCrystal: -1,
        seducedOrRedeemed: false,
        description:
          "Qui Gon Jinn is a unique card that flips a coin before attacking, resulting in +700 or -700 stats based on the outcome. He is a unpredictable but potentially strong card.",
      },
      {
        id: 13,
        name: "maul",
        attack: 2800,
        defence: 2000,
        image: "https://i.imgur.com/Lr6v5Ph.png",
        type: "epic_card",
        mana: 5,
        side: "dark",
        isDef: false,
        wasDef: false,
        maulCurse: { active: false, round: -1 },
        locked: { active: false, round: -1 },
        timesAttacked: 0,
        immune: false,
        forceChoke: 0,
        forcePull: false,
        sithBetrayal: -1,
        forcePush: -1,
        forcePull: false,
        kyberCrystal: -1,
        seducedOrRedeemed: false,
        description:
          "Dark Maul is a powerful card with a deadly ability. If he dies in battle, he can attach himself to the enemy and strike on the next turn, destroying the enemy card. His fearsome presence and strategic abilities make him a formidable opponent in any card game.",
      },
      {
        id: 14,
        name: "grievous",
        attack: 2500,
        defence: 2200,
        image: "https://i.imgur.com/wwV6GNb.png",
        type: "epic_card",
        mana: 5,
        side: "dark",
        isDef: false,
        wasDef: false,
        maulCurse: { active: false, round: -1 },
        locked: { active: false, round: -1 },
        timesAttacked: 0,
        immune: false,
        forceChoke: 0,
        forcePull: false,
        sithBetrayal: -1,
        forcePush: -1,
        forcePull: false,
        kyberCrystal: -1,
        seducedOrRedeemed: false,
        description:
          "General Grievous is a powerful card that summons two droids to fight alongside him when he is played. He is a formidable force on the battlefield, with strong leadership skills and strategic abilities.",
      },
      {
        id: 15,
        name: "darthvader",
        attack: 4000,
        defence: 3500,
        image: "https://i.imgur.com/zSeZ5EJ.png",
        type: "epic_card",
        mana: 9,
        side: "dark",
        isDef: false,
        wasDef: false,
        maulCurse: { active: false, round: -1 },
        locked: { active: false, round: -1 },
        timesAttacked: 0,
        immune: false,
        forceChoke: 0,
        forcePull: false,
        sithBetrayal: -1,
        forcePush: -1,
        forcePull: false,
        kyberCrystal: -1,
        seducedOrRedeemed: false,
        description:
          "Bring the Dark Side's deadliest warrior to the battlefield, where he can wipe out all enemies with a single command. Requires a Dark card to be played.",
      },
      {
        id: 16,
        name: "anakin",
        attack: 3500,
        defence: 3500,
        image: "https://i.imgur.com/9CIQ1kW.png",
        type: "epic_card",
        mana: 8,
        side: "light",
        isDef: false,
        wasDef: false,
        maulCurse: { active: false, round: -1 },
        locked: { active: false, round: -1 },
        timesAttacked: 0,
        immune: false,
        forceChoke: 0,
        forcePull: false,
        sithBetrayal: -1,
        forcePush: -1,
        forcePull: false,
        kyberCrystal: -1,
        seducedOrRedeemed: false,
        description:
          "Anakin is a powerful warrior with +100 attack after winning battles. He is a shining beacon of strength, ready to lead you to victory.",
      },
      {
        id: 17,
        name: "darthsidious",
        attack: 3600,
        defence: 3200,
        image: "https://i.imgur.com/hdQeIO7.png",
        type: "epic_card",
        mana: 8,
        side: "dark",
        isDef: false,
        wasDef: false,
        revived: 0,
        maulCurse: { active: false, round: -1 },
        locked: { active: false, round: -1 },
        timesAttacked: 0,
        immune: false,
        forceChoke: 0,
        forcePull: false,
        sithBetrayal: -1,
        forcePush: -1,
        forcePull: false,
        kyberCrystal: -1,
        seducedOrRedeemed: false,
        description:
          "Darth Sidious is a powerful card that returns to the field once after being defeated in battle. He is a formidable presence, ready to lead you to victory.",
      },
      {
        id: 18,
        name: "yoda",
        attack: 3800,
        defence: 3000,
        image: "https://i.imgur.com/0CakKMs.png",
        type: "epic_card",
        mana: 8,
        side: "light",
        isDef: false,
        wasDef: false,
        maulCurse: { active: false, round: -1 },
        locked: { active: false, round: -1 },
        timesAttacked: 0,
        immune: false,
        forceChoke: 0,
        forcePull: false,
        sithBetrayal: -1,
        forcePush: -1,
        forcePull: false,
        kyberCrystal: -1,
        seducedOrRedeemed: false,
        description:
          "Yoda is a powerful card that cannot be killed or debuffed by special effects. He is a shining beacon of resilience, his indomitable spirit guiding you to victory.",
      },
      {
        id: 19,
        name: "obiwan",
        attack: 2500,
        defence: 4000,
        image: "https://i.imgur.com/5PrvfKs.png",
        type: "epic_card",
        mana: 7,
        side: "light",
        isDef: false,
        wasDef: false,
        maulCurse: { active: false, round: -1 },
        locked: { active: false, round: -1 },
        timesAttacked: 0,
        immune: false,
        forceChoke: 0,
        forcePull: false,
        sithBetrayal: -1,
        forcePush: -1,
        forcePull: false,
        kyberCrystal: -1,
        seducedOrRedeemed: false,
        description:
          "Obi-Wan Kenobi is a powerful card with defense equal to the highest enemy attack. He is a versatile warrior, ready to adapt to any situation and emerge victorious.",
      },
      {
        id: 20,
        name: "luke",
        attack: 3500,
        defence: 2800,
        image: "https://i.imgur.com/33ebuKF.png",
        type: "epic_card",
        mana: 7,
        side: "light",
        isDef: false,
        wasDef: false,
        maulCurse: { active: false, round: -1 },
        locked: { active: false, round: -1 },
        timesAttacked: 0,
        immune: false,
        forceChoke: 0,
        forcePull: false,
        sithBetrayal: -1,
        forcePush: -1,
        forcePull: false,
        kyberCrystal: -1,
        seducedOrRedeemed: false,
        description:
          "Luke Skywalker is a powerful card that gains +100 attack for each dark side card on the field. He becomes stronger as the battle progresses and is a valuable asset in any deck.",
      },
      {
        id: 21,
        name: "windu",
        attack: 3000,
        defence: 3000,
        image: "https://i.imgur.com/33ebuKF.png",
        type: "epic_card",
        mana: 6,
        side: "no_side",
        isDef: false,
        wasDef: false,
        maulCurse: { active: false, round: -1 },
        locked: { active: false, round: -1 },
        timesAttacked: 0,
        immune: false,
        forceChoke: 0,
        forcePull: false,
        sithBetrayal: -1,
        forcePush: -1,
        forcePull: false,
        kyberCrystal: -1,
        seducedOrRedeemed: false,
        description:
          "Mace Windu is a powerful and adaptable card, his ability to utilize both light and dark spells giving him a wide range of options in battle. His versatility and strength make him a valuable asset to have in any deck.",
      },
      {
        id: 22,
        name: "dooku",
        attack: 3300,
        defence: 2600,
        image: "https://i.imgur.com/pwU3g3l.png",
        type: "epic_card",
        mana: 6,
        side: "dark",
        isDef: false,
        wasDef: false,
        maulCurse: { active: false, round: -1 },
        locked: { active: false, round: -1 },
        timesAttacked: 0,
        immune: false,
        forceChoke: 0,
        forcePull: false,
        sithBetrayal: -1,
        forcePush: -1,
        forcePull: false,
        kyberCrystal: -1,
        seducedOrRedeemed: false,
        description:
          "Count Dooku is a powerful card that can attack twice per turn, but cannot attack directly to points. He is a formidable opponent, but his limitations can also be a hindrance.",
      },
      {
        id: 23,
        name: "kyloren",
        attack: 3000,
        defence: 2800,
        image: "https://i.imgur.com/CTjr8WC.png",
        type: "epic_card",
        mana: 6,
        side: "dark",
        isDef: false,
        wasDef: false,
        maulCurse: { active: false, round: -1 },
        locked: { active: false, round: -1 },
        timesAttacked: 0,
        immune: false,
        forceChoke: 0,
        forcePull: false,
        sithBetrayal: -1,
        forcePush: -1,
        forcePull: false,
        kyberCrystal: -1,
        seducedOrRedeemed: false,
        description:
          "Kylo Ren is a powerful card that reveals enemy hand cards while in play. He is a valuable asset, providing valuable information about your opponent's strategies.",
      },
      {
        id: 24,
        name: "ahsoka",
        attack: 3000,
        defence: 2500,
        image: "https://i.imgur.com/xAmdUk9.png",
        type: "epic_card",
        mana: 5,
        side: "no_side",
        isDef: false,
        wasDef: false,
        maulCurse: { active: false, round: -1 },
        locked: { active: false, round: -1 },
        timesAttacked: 0,
        immune: false,
        forceChoke: 0,
        forcePull: false,
        sithBetrayal: -1,
        forcePush: -1,
        forcePull: false,
        kyberCrystal: -1,
        seducedOrRedeemed: false,
        description:
          "Ahsoka Tano is a powerful card that gains +300 attack when battling Light cards and decreases enemy stats by -500 when battling Dark cards. She is a formidable opponent and a valuable asset in any game.",
      },
      {
        id: 25,
        name: "rey",
        attack: 3200,
        defence: 2000,
        image: "https://i.imgur.com/cqclRMW.png",
        type: "epic_card",
        mana: 6,
        side: "light",
        isDef: false,
        wasDef: false,
        maulCurse: { active: false, round: -1 },
        locked: { active: false, round: -1 },
        timesAttacked: 0,
        immune: false,
        forceChoke: 0,
        forcePull: false,
        sithBetrayal: -1,
        forcePush: -1,
        forcePull: false,
        kyberCrystal: -1,
        seducedOrRedeemed: false,
        description:
          "Rey Skywalker is a powerful card that can attack directly to points and switches to defense after every attack. She is a strategic and versatile warrior, ready to lead you to victory.",
      },
      {
        id: 26,
        name: "quigon",
        attack: 2800,
        defence: 2200,
        image: "https://i.imgur.com/4sWrMXj.png",
        type: "epic_card",
        mana: 5,
        side: "light",
        isDef: false,
        wasDef: false,
        maulCurse: { active: false, round: -1 },
        locked: { active: false, round: -1 },
        timesAttacked: 0,
        immune: false,
        forceChoke: 0,
        forcePull: false,
        sithBetrayal: -1,
        forcePush: -1,
        forcePull: false,
        kyberCrystal: -1,
        seducedOrRedeemed: false,
        description:
          "Qui Gon Jinn is a unique card that flips a coin before attacking, resulting in +700 or -700 stats based on the outcome. He is a unpredictable but potentially strong card.",
      },
      {
        id: 27,
        name: "maul",
        attack: 2800,
        defence: 2000,
        image: "https://i.imgur.com/Lr6v5Ph.png",
        type: "epic_card",
        mana: 5,
        side: "dark",
        isDef: false,
        wasDef: false,
        maulCurse: { active: false, round: -1 },
        locked: { active: false, round: -1 },
        timesAttacked: 0,
        immune: false,
        forceChoke: 0,
        forcePull: false,
        sithBetrayal: -1,
        forcePush: -1,
        forcePull: false,
        kyberCrystal: -1,
        seducedOrRedeemed: false,
        description:
          "Dark Maul is a powerful card with a deadly ability. If he dies in battle, he can attach himself to the enemy and strike on the next turn, destroying the enemy card. His fearsome presence and strategic abilities make him a formidable opponent in any card game.",
      },
      {
        id: 28,
        name: "grievous",
        attack: 2500,
        defence: 2200,
        image: "https://i.imgur.com/wwV6GNb.png",
        type: "epic_card",
        mana: 5,
        side: "dark",
        isDef: false,
        wasDef: false,
        maulCurse: { active: false, round: -1 },
        locked: { active: false, round: -1 },
        timesAttacked: 0,
        immune: false,
        forceChoke: 0,
        forcePull: false,
        sithBetrayal: -1,
        forcePush: -1,
        forcePull: false,
        kyberCrystal: -1,
        seducedOrRedeemed: false,
        description:
          "General Grievous is a powerful card that summons two droids to fight alongside him when he is played. He is a formidable force on the battlefield, with strong leadership skills and strategic abilities.",
      },
    ],
  };
  