export const someCards = {
  heros: [
    {
      id: 1,
      name: "darthvader",
      attack: 4000,
      defence: 3500,
      image: "https://i.imgur.com/zSeZ5EJ.png",
      type: "epic_card",
      mana: 9,
      side: "dark",
      isDef: false,
      wasDef: false,
      maulCurse: { active: false, round: -1 },
      locked: { active: false, round: -1 },
      timesAttacked: 0,
      immune: false,
      forceChoke: 0,
      forcePull: false,
      sithBetrayal: -1,
      forcePush: -1,
      forcePull: false,
      kyberCrystal: -1,
      seducedOrRedeemed: false,
      description:
        "Bring the Dark Side's deadliest warrior to the battlefield, where he can wipe out all enemies with a single command. Requires a Dark card to be played.",
    },
    {
      id: 2,
      name: "anakin",
      attack: 3500,
      defence: 3500,
      image: "https://i.imgur.com/9CIQ1kW.png",
      type: "epic_card",
      mana: 8,
      side: "light",
      isDef: false,
      wasDef: false,
      maulCurse: { active: false, round: -1 },
      locked: { active: false, round: -1 },
      timesAttacked: 0,
      immune: false,
      forceChoke: 0,
      forcePull: false,
      sithBetrayal: -1,
      forcePush: -1,
      forcePull: false,
      kyberCrystal: -1,
      seducedOrRedeemed: false,
      description:
        "Anakin is a powerful warrior with +100 attack after winning battles. He is a shining beacon of strength, ready to lead you to victory.",
    },
    {
      id: 3,
      name: "darthsidious",
      attack: 3600,
      defence: 3200,
      image: "https://i.imgur.com/hdQeIO7.png",
      type: "epic_card",
      mana: 8,
      side: "dark",
      isDef: false,
      wasDef: false,
      revived: 0,
      maulCurse: { active: false, round: -1 },
      locked: { active: false, round: -1 },
      timesAttacked: 0,
      immune: false,
      forceChoke: 0,
      forcePull: false,
      sithBetrayal: -1,
      forcePush: -1,
      forcePull: false,
      kyberCrystal: -1,
      seducedOrRedeemed: false,
      description:
        "Darth Sidious is a powerful card that returns to the field once after being defeated in battle. He is a formidable presence, ready to lead you to victory.",
    },
    {
      id: 4,
      name: "yoda",
      attack: 3800,
      defence: 3000,
      image: "https://i.imgur.com/0CakKMs.png",
      type: "epic_card",
      mana: 8,
      side: "light",
      isDef: false,
      wasDef: false,
      maulCurse: { active: false, round: -1 },
      locked: { active: false, round: -1 },
      timesAttacked: 0,
      immune: false,
      forceChoke: 0,
      forcePull: false,
      sithBetrayal: -1,
      forcePush: -1,
      forcePull: false,
      kyberCrystal: -1,
      seducedOrRedeemed: false,
      description:
        "Yoda is a powerful card that cannot be killed or debuffed by special effects. He is a shining beacon of resilience, his indomitable spirit guiding you to victory.",
    },
    {
      id: 5,
      name: "obiwan",
      attack: 2500,
      defence: 4000,
      image: "https://i.imgur.com/5PrvfKs.png",
      type: "epic_card",
      mana: 7,
      side: "light",
      isDef: false,
      wasDef: false,
      maulCurse: { active: false, round: -1 },
      locked: { active: false, round: -1 },
      timesAttacked: 0,
      immune: false,
      forceChoke: 0,
      forcePull: false,
      sithBetrayal: -1,
      forcePush: -1,
      forcePull: false,
      kyberCrystal: -1,
      seducedOrRedeemed: false,
      description:
        "Obi-Wan Kenobi is a powerful card with defense equal to the highest enemy attack. He is a versatile warrior, ready to adapt to any situation and emerge victorious.",
    },
    {
      id: 7,
      name: "windu",
      attack: 3000,
      defence: 3000,
      image: "https://i.imgur.com/33ebuKF.png",
      type: "epic_card",
      mana: 6,
      side: "no_side",
      isDef: false,
      wasDef: false,
      maulCurse: { active: false, round: -1 },
      locked: { active: false, round: -1 },
      timesAttacked: 0,
      immune: false,
      forceChoke: 0,
      forcePull: false,
      sithBetrayal: -1,
      forcePush: -1,
      forcePull: false,
      kyberCrystal: -1,
      seducedOrRedeemed: false,
      description:
        "Mace Windu is a powerful and adaptable card, his ability to utilize both light and dark spells giving him a wide range of options in battle. His versatility and strength make him a valuable asset to have in any deck.",
    },
    {
      id: 8,
      name: "dooku",
      attack: 3300,
      defence: 2600,
      image: "https://i.imgur.com/pwU3g3l.png",
      type: "epic_card",
      mana: 6,
      side: "dark",
      isDef: false,
      wasDef: false,
      maulCurse: { active: false, round: -1 },
      locked: { active: false, round: -1 },
      timesAttacked: 0,
      immune: false,
      forceChoke: 0,
      forcePull: false,
      sithBetrayal: -1,
      forcePush: -1,
      forcePull: false,
      kyberCrystal: -1,
      seducedOrRedeemed: false,
      description:
        "Count Dooku is a powerful card that can attack twice per turn, but cannot attack directly to points. He is a formidable opponent, but his limitations can also be a hindrance.",
    },
    {
      id: 9,
      name: "kyloren",
      attack: 3000,
      defence: 2800,
      image: "https://i.imgur.com/CTjr8WC.png",
      type: "epic_card",
      mana: 6,
      side: "dark",
      isDef: false,
      wasDef: false,
      maulCurse: { active: false, round: -1 },
      locked: { active: false, round: -1 },
      timesAttacked: 0,
      immune: false,
      forceChoke: 0,
      forcePull: false,
      sithBetrayal: -1,
      forcePush: -1,
      forcePull: false,
      kyberCrystal: -1,
      seducedOrRedeemed: false,
      description:
        "Kylo Ren is a powerful card that reveals enemy hand cards while in play. He is a valuable asset, providing valuable information about your opponent's strategies.",
    },
    {
      id: 10,
      name: "ahsoka",
      attack: 3000,
      defence: 2500,
      image: "https://i.imgur.com/xAmdUk9.png",
      type: "epic_card",
      mana: 5,
      side: "no_side",
      isDef: false,
      wasDef: false,
      maulCurse: { active: false, round: -1 },
      locked: { active: false, round: -1 },
      timesAttacked: 0,
      immune: false,
      forceChoke: 0,
      forcePull: false,
      sithBetrayal: -1,
      forcePush: -1,
      forcePull: false,
      kyberCrystal: -1,
      seducedOrRedeemed: false,
      description:
        "Ahsoka Tano is a powerful card that gains +300 attack when battling Light cards and decreases enemy stats by -500 when battling Dark cards. She is a formidable opponent and a valuable asset in any game.",
    },
    {
      id: 11,
      name: "rey",
      attack: 3200,
      defence: 2000,
      image: "https://i.imgur.com/cqclRMW.png",
      type: "epic_card",
      mana: 6,
      side: "light",
      isDef: false,
      wasDef: false,
      maulCurse: { active: false, round: -1 },
      locked: { active: false, round: -1 },
      timesAttacked: 0,
      immune: false,
      forceChoke: 0,
      forcePull: false,
      sithBetrayal: -1,
      forcePush: -1,
      forcePull: false,
      kyberCrystal: -1,
      seducedOrRedeemed: false,
      description:
        "Rey Skywalker is a powerful card that can attack directly to points and switches to defense after every attack. She is a strategic and versatile warrior, ready to lead you to victory.",
    },
    {
      id: 12,
      name: "quigon",
      attack: 2800,
      defence: 2200,
      image: "https://i.imgur.com/4sWrMXj.png",
      type: "epic_card",
      mana: 5,
      side: "light",
      isDef: false,
      wasDef: false,
      maulCurse: { active: false, round: -1 },
      locked: { active: false, round: -1 },
      timesAttacked: 0,
      immune: false,
      forceChoke: 0,
      forcePull: false,
      sithBetrayal: -1,
      forcePush: -1,
      forcePull: false,
      kyberCrystal: -1,
      seducedOrRedeemed: false,
      description:
        "Qui Gon Jinn is a unique card that flips a coin before attacking, resulting in +700 or -700 stats based on the outcome. He is a unpredictable but potentially strong card.",
    },
    {
      id: 13,
      name: "maul",
      attack: 2800,
      defence: 2000,
      image: "https://i.imgur.com/Lr6v5Ph.png",
      type: "epic_card",
      mana: 5,
      side: "dark",
      isDef: false,
      wasDef: false,
      maulCurse: { active: false, round: -1 },
      locked: { active: false, round: -1 },
      timesAttacked: 0,
      immune: false,
      forceChoke: 0,
      forcePull: false,
      sithBetrayal: -1,
      forcePush: -1,
      forcePull: false,
      kyberCrystal: -1,
      seducedOrRedeemed: false,
      description:
        "Dark Maul is a powerful card with a deadly ability. If he dies in battle, he can attach himself to the enemy and strike on the next turn, destroying the enemy card. His fearsome presence and strategic abilities make him a formidable opponent in any card game.",
    },
    {
      id: 20,
      name: "han_solo",
      attack: 1700,
      defence: 1400,
      image: "https://i.imgur.com/NOFyDng.png",
      type: "basic_card",
      mana: 2,
      side: "no_side",
      isDef: false,
      wasDef: false,
      maulCurse: { active: false, round: -1 },
      locked: { active: false, round: -1 },
      timesAttacked: 0,
      immune: false,
      forceChoke: 0,
      forcePull: false,
      sithBetrayal: -1,
      forcePush: -1,
      forcePull: false,
      kyberCrystal: -1,
      seducedOrRedeemed: false,
      description:
        "Han Solo is a smuggler and pilot who becomes a key member of the Rebel Alliance.",
    },
    {
      id: 21,
      name: "padme",
      attack: 1600,
      defence: 1200,
      image: "https://i.imgur.com/4qvNTrH.png",
      type: "basic_card",
      mana: 2,
      side: "no_side",
      isDef: false,
      wasDef: false,
      maulCurse: { active: false, round: -1 },
      locked: { active: false, round: -1 },
      timesAttacked: 0,
      immune: false,
      forceChoke: 0,
      forcePull: false,
      sithBetrayal: -1,
      forcePush: -1,
      forcePull: false,
      kyberCrystal: -1,
      seducedOrRedeemed: false,
      description:
        "Padmé is a diplomat and politician from the planet Naboo known for her strong sense of justice and dedication to peace.",
    },
    {
      id: 22,
      name: "grogu",
      attack: 1500,
      defence: 1200,
      image: "https://i.imgur.com/nrHeR0W.png",
      type: "basic_card",
      mana: 2,
      side: "no_side",
      isDef: false,
      wasDef: false,
      maulCurse: { active: false, round: -1 },
      locked: { active: false, round: -1 },
      timesAttacked: 0,
      immune: false,
      forceChoke: 0,
      forcePull: false,
      sithBetrayal: -1,
      forcePush: -1,
      forcePull: false,
      kyberCrystal: -1,
      seducedOrRedeemed: false,
      description:
        "Despite his small size, Grogu is a formidable force in the Star Wars universe, inspiring loyalty and love in all who encounter him.",
    },
    {
      id: 23,
      name: "r2d2",
      attack: 1200,
      defence: 1200,
      image: "https://i.imgur.com/Wv39w8V.png",
      type: "basic_card",
      mana: 1,
      side: "no_side",
      isDef: false,
      wasDef: false,
      maulCurse: { active: false, round: -1 },
      locked: { active: false, round: -1 },
      timesAttacked: 0,
      immune: false,
      forceChoke: 0,
      forcePull: false,
      sithBetrayal: -1,
      forcePush: -1,
      forcePull: false,
      kyberCrystal: -1,
      seducedOrRedeemed: false,
      description:
        "R2-D2 is a small, intelligent robot. It communicates through beeps and whistles and is known for its resourcefulness and bravery.",
    },
    {
      id: 24,
      name: "bb8",
      attack: 1100,
      defence: 1100,
      image: "https://i.imgur.com/wWBewqN.png",
      type: "basic_card",
      mana: 1,
      side: "no_side",
      isDef: false,
      wasDef: false,
      maulCurse: { active: false, round: -1 },
      locked: { active: false, round: -1 },
      timesAttacked: 0,
      immune: false,
      forceChoke: 0,
      forcePull: false,
      sithBetrayal: -1,
      forcePush: -1,
      forcePull: false,
      kyberCrystal: -1,
      seducedOrRedeemed: false,
      description:
        "BB-8 is a spherical droid with a domed head that can move independently of its body.",
    },
    {
      id: 25,
      name: "c3po",
      attack: 1100,
      defence: 1000,
      image: "https://i.imgur.com/0lvAC6X.png",
      type: "basic_card",
      mana: 1,
      side: "no_side",
      isDef: false,
      wasDef: false,
      maulCurse: { active: false, round: -1 },
      locked: { active: false, round: -1 },
      timesAttacked: 0,
      immune: false,
      forceChoke: 0,
      forcePull: false,
      sithBetrayal: -1,
      forcePush: -1,
      forcePull: false,
      kyberCrystal: -1,
      seducedOrRedeemed: false,
      description:
        "C-3PO is a protocol droid designed to assist with etiquette, customs, and translation, and is fluent in over six million forms of communication.",
    },
    {
      id: 14,
      name: "grievous",
      attack: 2500,
      defence: 2200,
      image: "https://i.imgur.com/wwV6GNb.png",
      type: "epic_card",
      mana: 5,
      side: "dark",
      isDef: false,
      wasDef: false,
      maulCurse: { active: false, round: -1 },
      locked: { active: false, round: -1 },
      timesAttacked: 0,
      immune: false,
      forceChoke: 0,
      forcePull: false,
      sithBetrayal: -1,
      forcePush: -1,
      forcePull: false,
      kyberCrystal: -1,
      seducedOrRedeemed: false,
      description:
        "General Grievous is a powerful card that summons two droids to fight alongside him when he is played. He is a formidable force on the battlefield, with strong leadership skills and strategic abilities.",
    },
    {
      id: 6,
      name: "luke",
      attack: 3500,
      defence: 2800,
      image: "https://i.imgur.com/33ebuKF.png",
      type: "epic_card",
      mana: 7,
      side: "light",
      isDef: false,
      wasDef: false,
      maulCurse: { active: false, round: -1 },
      locked: { active: false, round: -1 },
      timesAttacked: 0,
      immune: false,
      forceChoke: 0,
      forcePull: false,
      sithBetrayal: -1,
      forcePush: -1,
      forcePull: false,
      kyberCrystal: -1,
      seducedOrRedeemed: false,
      description:
        "Luke Skywalker is a powerful card that gains +100 attack for each dark side card on the field. He becomes stronger as the battle progresses and is a valuable asset in any deck.",
    },
    {
      id: 29,
      name: "special_galacticrepublic",
      image: "https://i.imgur.com/rlAJKZp.png",
      type: "special",
      mana: 6,
      description:
        "Galactic Republic: This powerful force card allows you to call upon the strength and unity of the Galactic Republic to increase the stats of all light cards in play by +200. Whether you're facing down a formidable enemy or simply looking to give your light side forces a boost, the Galactic Republic is a valuable ally in any battle. However, it can only be used if you have at least one light card on the field, so plan your strategy carefully and choose your targets wisely. May the force be with you.",
    },
  ],
};
